DEVEL15-debian-packaging-update-20080220
LICENSE IPL10

Russ' metadata, repacked into our tree


(cherry picked from commit cd9ce022ee97bee809e840be8612aafb2cbfc6b8)

diff --git a/src/packaging/Debian/openafs-fileserver.postrm b/src/packaging/Debian/openafs-fileserver.postrm
--- a/src/packaging/Debian/openafs-fileserver.postrm
+++ b/src/packaging/Debian/openafs-fileserver.postrm
@@ -1,40 +1,46 @@
 #! /bin/sh
-# postrm script for openafs
+# postrm script for openafs-fileserver
 #
-# see: dh_installdeb(1)
+# Purges various extra configuration files and data files created by the
+# package.  Whether to purge KeyFile is a bit iffy since the user created it
+# with asetkey or with bos addkey, but it always exists for any running server
+# and we shouldn't be losing any critical data.
+#
+# We intentionally don't remove NetInfo and NetRestrict in
+# /var/lib/openafs/local since those are created separately by the user and
+# may contain information not stored elsewhere.
 
 set -e
 
-# summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
-# for details, see /usr/share/doc/packaging-manual/
-
 case "$1" in
 purge)
-    rm /etc/openafs/server/ThisCell 2>/dev/null || true
-    (cd /etc/openafs/server && rm CellServDB UserList) 2>/dev/null ||true
-    (cd /etc/openafs/server-local && rm BosConfig) 2>/dev/null ||true
+    for file in CellServDB CellServDB.old KeyFile ThisCell UserList ; do
+        rm -f "/etc/openafs/server/$file"
+    done
+    for file in SALVAGE.fs fssync.sock salvage.lock sysid sysid.old ; do
+        rm -f "/var/lib/openafs/local/$file"
+    done
+    rm -f /etc/openafs/BosConfig
+    for file in BosLog FileLog SalvageLog VolserLog ; do
+        rm -f "/var/log/openafs/$file"
+        rm -f "/var/log/openafs/$file.old"
+    done
+
+    # Clean up after files left behind from older versions of the package.
+    if [ -d /etc/openafs/server-local ] ; then
+        for file in SALVAGE.fs fssync.sock salvage.lock sysid sysid.old ; do
+            rm -f "/etc/openafs/server-local/$file"
+        done
+        rmdir --ignore-fail-on-non-empty /etc/openafs/server-local
+    fi
     ;;
-       remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
 
+remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
 
-        ;;
-
-    *)
-        echo "postrm called with unknown argument \`$1'" >&2
-        exit 0
-
+*)
+    echo "postrm called with unknown argument \`$1'" >&2
+    exit 0
 esac
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
 #DEBHELPER#
-
