* Diagnose unsupported architectures earlier and with a clearer error.   * Suppress error messages from a missing kernel version header since     they occur normally when doing the regular package build and are just     confusing.  Instead, print an error in kern-sysname and abort if the     kernel version could not be determined.

diff --git a/debian/sysname b/debian/sysname
--- a/debian/sysname
+++ b/debian/sysname
@@ -31,6 +31,7 @@ sparc|sparc64)
     echo sparc_linux24
     ;;
 *)
-    echo ERROr:  sysname not yet known
+    echo "ERROR: unsupported architecture" >&2
+    echo UNKNOWN
     exit 1
 esac
