autoconf: detect ctf-tools and add ctf to libafs
CTF is a reduced form of debug information similar to DWARF and stab. It
describes types and function prototypes. The principal objective of the
format is to shrink the data size as much as possible so that it could
be included in a production environment. MDB, DTrace, and other tools
use CTF debug information to read and display structures correctly.

This commit introduces a new configure option called --with-ctf-tools.
This option can be used to specify an alternative path where the tools
can be found. If the path is not provided, the tools will be searched
in a set of default directories (including $PATH). The CTF debugging
information will only be included if the corresponding --enable-debug /
--enable-debug-kernel is specified.

Note: at the moment, the Solaris kernel module is the only module
benefited by this commit.

Reviewed-on: https://gerrit.openafs.org/12680
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>
(cherry picked from commit 88cb536f99dc58fdbeb9fa6c47c26774241a0cb6)

Change-Id: I174347370a83b31f68d2631c965e17d72b438cd1
Reviewed-on: https://gerrit.openafs.org/12902
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Benjamin Kaduk <kaduk@mit.edu>

diff --git a/src/config/Makefile.config.in b/src/config/Makefile.config.in
--- a/src/config/Makefile.config.in
+++ b/src/config/Makefile.config.in
@@ -51,6 +51,8 @@ FSINCLUDES = @FSINCLUDES@
 GENCAT = @GENCAT@
 INCLUDE_LIBINTL = @INCLUDE_libintl@
 KERN_DBG = @KERN_DBG@
+CTFCONVERT = @CTFCONVERT@
+CTFMERGE = @CTFMERGE@
 KERN_OPTMZ = @KERN_OPTMZ@
 LD = @LD@
 LDFLAGS_roken = @LDFLAGS_roken@
@@ -315,4 +317,34 @@ LT_CLEAN=$(RM) -rf .lwp .libs *.la *.lo
 
 AFS_LDRULE         =$(RUN_LD) $(CC) $(AFS_LDFLAGS) $(AFS_CFLAGS) $(LDFLAGS_$(@)) -o $@
 AFS_LDRULE_NOQ =$(RUN_LD_NOQ) $(CC) $(AFS_LDFLAGS) $(AFS_CFLAGS) $(LDFLAGS_$(@)) -o $@
+
+RUN_CTFCONVERT=@RUN_CTFCONVERT() { \
+    CTFLABEL=$$1 ; \
+    CTFDBG=$$2 ; \
+    shift ; shift ; \
+    if test "x$${CTFDBG}" = "x" ; then exit 0; fi; \
+    if test "x${CTFCONVERT}" = "x" ; then exit 0; fi; \
+    if test "x${CTFMERGE}" = "x" ; then \
+        echo "refusing to run ctfconvert; missing ctfmerge"; \
+        exit 1; \
+    fi; \
+    for t in $$@ ; do \
+        echo "${CTFCONVERT} -g -l $${CTFLABEL} $$t"; \
+        ${CTFCONVERT} -g -l $${CTFLABEL} $$t; \
+    done ; \
+} ; RUN_CTFCONVERT
+
+RUN_CTFMERGE=@RUN_CTFMERGE () { \
+    CTFLABEL=$$1 ; \
+    CTFDBG=$$2 ; \
+    shift ; shift ; \
+    if test "x$${CTFDBG}" = "x" ; then exit 0; fi; \
+    if test "x${CTFMERGE}" = "x" ; then exit 0; fi; \
+    if test "x${CTFCONVERT}" = "x" ; then \
+        echo "refusing to run ctfmerge; missing ctfconvert"; \
+        exit 1; \
+    fi; \
+    echo "$(CTFMERGE) -g -l $${CTFLABEL} -o $$@"; \
+    $(CTFMERGE) -g -l $${CTFLABEL} -o $$@; \
+} ; RUN_CTFMERGE
 
